### ISSUE TITLE
The menu must close when a option is clicked

### ISSUE THREAD

**Issue by DevDario** [codewithsadee/jack-portfolio#1]
The menu in the mobile version isn't closing when an option is clicked.

**Comment by YazanFarrah** [comment]
add this code to the script.js in JS folder and you're good to go

`const navLinks = document.querySelectorAll(".navbar-link");
navLinks.forEach(link => {
  link.addEventListener("click", function () {
    // Close the navbar
    navToggleBtn.classList.remove("active");
    navbar.classList.remove("active");
    document.body.classList.remove("active");
  });
});`
